### ISSUE TITLE
URL http://grylloblattodea.speciesfile.org/ still connecting to archived site.

### ISSUE THREAD

**Issue by hhopkins77** [sfg-taxonpages/grylloblattodea#1]
Hope I have filed this issue in the right spot. When using this URL http://grylloblattodea.speciesfile.org/ I am connected to the old species file website.

**Comment by mjy** [comment]
Thanks @hhopkins77 I think I closed the wrong issue there.  We'll tackle it from this issue.

**Comment by LocoDelAssembly** [comment]
Site has been deployed on September 26th. If it is still showing old site for you please let us know @hhopkins77
